/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class intarray : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal intarray(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(intarray obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~intarray() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
        swigCMemOwn = false;
        mapscriptPINVOKE.delete_intarray(swigCPtr);
      }
      swigCPtr = new HandleRef(null, IntPtr.Zero);
      GC.SuppressFinalize(this);
    }
  }

  public intarray(int nelements) : this(mapscriptPINVOKE.new_intarray(nelements), true) {
  }

  public int getitem(int index) {
    int ret = mapscriptPINVOKE.intarray_getitem(swigCPtr, index);
    return ret;
  }

  public void setitem(int index, int value) {
    mapscriptPINVOKE.intarray_setitem(swigCPtr, index, value);
  }

  public SWIGTYPE_p_int cast() {
    IntPtr cPtr = mapscriptPINVOKE.intarray_cast(swigCPtr);
    SWIGTYPE_p_int ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_int(cPtr, false);
    return ret;
  }

  public static intarray frompointer(SWIGTYPE_p_int t) {
    IntPtr cPtr = mapscriptPINVOKE.intarray_frompointer(SWIGTYPE_p_int.getCPtr(t));
    intarray ret = (cPtr == IntPtr.Zero) ? null : new intarray(cPtr, false);
    return ret;
  }

}
