/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class labelCacheSlotObj : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal labelCacheSlotObj(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(labelCacheSlotObj obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~labelCacheSlotObj() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
        swigCMemOwn = false;
        mapscriptPINVOKE.delete_labelCacheSlotObj(swigCPtr);
      }
      swigCPtr = new HandleRef(null, IntPtr.Zero);
      GC.SuppressFinalize(this);
    }
  }

  public labelCacheMemberObj labels {
    get {
      IntPtr cPtr = mapscriptPINVOKE.labelCacheSlotObj_labels_get(swigCPtr);
      labelCacheMemberObj ret = (cPtr == IntPtr.Zero) ? null : new labelCacheMemberObj(cPtr, false);
      if (mapscriptPINVOKE.SWIGPendingException.Pending) throw mapscriptPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public int numlabels {
    get {
      int ret = mapscriptPINVOKE.labelCacheSlotObj_numlabels_get(swigCPtr);
      if (mapscriptPINVOKE.SWIGPendingException.Pending) throw mapscriptPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public int cachesize {
    get {
      int ret = mapscriptPINVOKE.labelCacheSlotObj_cachesize_get(swigCPtr);
      if (mapscriptPINVOKE.SWIGPendingException.Pending) throw mapscriptPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public markerCacheMemberObj markers {
    get {
      IntPtr cPtr = mapscriptPINVOKE.labelCacheSlotObj_markers_get(swigCPtr);
      markerCacheMemberObj ret = (cPtr == IntPtr.Zero) ? null : new markerCacheMemberObj(cPtr, false);
      if (mapscriptPINVOKE.SWIGPendingException.Pending) throw mapscriptPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public int nummarkers {
    get {
      int ret = mapscriptPINVOKE.labelCacheSlotObj_nummarkers_get(swigCPtr);
      if (mapscriptPINVOKE.SWIGPendingException.Pending) throw mapscriptPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public int markercachesize {
    get {
      int ret = mapscriptPINVOKE.labelCacheSlotObj_markercachesize_get(swigCPtr);
      if (mapscriptPINVOKE.SWIGPendingException.Pending) throw mapscriptPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public labelCacheSlotObj() : this(mapscriptPINVOKE.new_labelCacheSlotObj(), true) {
    if (mapscriptPINVOKE.SWIGPendingException.Pending) throw mapscriptPINVOKE.SWIGPendingException.Retrieve();
  }

}
